version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cards_db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
networks:
  default:
    name: recard
    external: true